spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://192.168.209.135:3306/test #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
